# Generated by Django 5.0.2 on 2024-03-14 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App1", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="autordb",
            name="fecha_fallecimiento",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha Fallecimiento"
            ),
        ),
    ]
