# Generated by Django 5.0.2 on 2024-03-21 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("App1", "0002_alter_autordb_fecha_fallecimiento"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="frasedb",
            options={"verbose_name": "Frase", "verbose_name_plural": "Frases"},
        ),
    ]
